### PR TITLE
add python and os matrix

### PR DESCRIPTION
**Pull request by paskino**

### CODE REVIEW

**Comment by paskino** [comment]
@lauramurgatroyd do we need this? Conda handles it by itself, right?

**Comment by lauramurgatroyd** [comment]
yes, conda handles the builds for different python versions, if that is what you are asking

**Comment by lauramurgatroyd** [comment]
I think we can close this as we don't want to build variants?

**Comment by lauramurgatroyd** [comment]
Closing as we don't want to pin python versions

**Pull request closed without merging**
